### ISSUE TITLE
Not working on devices with a notch

### ISSUE THREAD

**Issue by matti142** [ilkerkesici/react-native-beauty-webview#1]
Hi,
this package is exactly what I'm looking for, but it's not working on devices with a notch (e.g. iPhone 11, 12, ..), because the closing and menu button are not reachable.
Instead of using the <View> component inside the <Modal>, you should use <SafeAreaView> to make sure, react native put some additional space between the webview and the notch.
Hope it can be fixed soon.

Regards

**Comment by ilkerkesici** [comment]
Hi, 

It was fixed by our contributors.

**Comment by mohit21dh** [comment]
@ilkerkesici I believe no new yarn or npm version is published for this fix, [here](https://www.npmjs.com/package/react-native-beauty-webview) the last published version is 2.0.0 which was 2 years back, could you please let me know how i can use this fix?

**Comment by Mohit21GoJs** [comment]
@ilkerkesici I believe no new yarn or npm version is published for this fix, [here](https://www.npmjs.com/package/react-native-beauty-webview) the last published version is 2.0.0 which was 2 years back, could you please let me know how i can use this fix?
