### ISSUE TITLE
Open "about:blank" when there's an URL.

### ISSUE THREAD

**Issue by hchen98** [ilkerkesici/react-native-beauty-webview#3]
I have encountered this issue where I have an API call inside the componentDidMount() to retrieve the URL. However, the URL does render as plain text but the URL for this Beauty Webview is undefined.

**Comment by NazimMertBilgi** [comment]
```
  {this.state.webViewOpen && <BeautyWebView
                    visible={this.state.webViewOpen} // Reguired for open and close
                    onPressClose={this.closeUrl} // Reguired for closing the modal
                    url={this.state.newsCurrentUrl}
                />}
```
@hchen98

**Comment by hchen98** [comment]
> ```
>   {this.state.webViewOpen && <BeautyWebView
>                     visible={this.state.webViewOpen} // Reguired for open and close
>                     onPressClose={this.closeUrl} // Reguired for closing the modal
>                     url={this.state.newsCurrentUrl}
>                 />}
> ```
> 
> @hchen98

Hi there, thank you for replying. I already found an alternative solution for this.
