### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by esadkrs** [ilkerkesici/react-native-beauty-webview#8]
It'd be very helpful to use the `Incognito property` in `WebView` for `clearing the cache`

Here is the [`source code`]( https://github.com/react-native-webview/react-native-webview/blob/cd42aa7f1110edb13d07978badd6d52e386d145c/src/WebViewTypes.ts#L278-L307) on `react-native-webview` repo.

**Comment by ilkerkesici** [comment]
We supported it new version.
